spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklistdb
    username: taskuser
    password: taskpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # creates tables automatically on the first run
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
