spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklistdb
    username: taskuser
    password: taskpass

  jpa:
    hibernate:
      ddl-auto: update  # creates tables automatically on the first run
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
server:
  port: 8080
